reshufflehq/reshuffle

babel-macro/package.json, babel-macro/src/macro.ts, babel-macro/src/test/backend/mockBackend.js, babel-macro/src/test/backend/mockTypeScriptBackend.ts, babel-macro/src/test/macro.spec.ts
=> Support compiled TypeScript

.circleci/config.yml, babel-macro/package.json, babel-macro/src/test/macro.spec.ts, common/changes/@binaris/shift-babel-macro/circle_2019-06-26-11-40.json, common/changes/@binaris/shift-babel-macro/circle_2019-06-26-12-00.json, common/changes/@binaris/shift-fetch-runtime/circle_2019-06-26-12-00.json, common/changes/@binaris/shift-local-proxy/circle_2019-06-26-12-00.json, fetch-runtime/package.json, local-proxy/package.json
=> Add Circle CI integration

babel-macro/src/macro.ts, babel-macro/src/test/macro.spec.ts, common/changes/@binaris/shift-babel-macro/change-error-text_2019-06-27-13-58.json
=> Rephrase error text

babel-macro/src/macro.ts, common/changes/@binaris/shift-babel-macro/master_2019-07-01-18-11.json, common/changes/@binaris/shift-fetch-runtime/master_2019-07-01-18-11.json, common/config/rush/shrinkwrap.yaml, fetch-runtime/package.json, fetch-runtime/src/index.ts, fetch-runtime/tsconfig.json
tested manually by importing a newly generated packed tgz
=> Use typescript in fetch runtime

common/changes/@binaris/shift-db/master_2019-07-02-12-28.json, common/changes/@binaris/shift-fetch-runtime/master_2019-07-02-12-28.json, common/changes/@binaris/shift-local-proxy/master_2019-07-02-12-28.json, db/package.json, fetch-runtime/package.json, local-proxy/package.json
=> Limit distributed files

.circleci/config.yml, common/changes/rush-update/change-auto-update-dep-job_2019-07-10-09-22.json, tools/rush-update/src/cli.ts, tools/rush-update/src/github.ts, tools/rush-update/src/main.ts
need to run `rush publish -a -b master -p --npm-auth-token $(aws s3 cp s3://secrets.binaris/npm -)` after merging
=> Run update_npm_dependencies weekly instead of nightly

babel-macro/tsconfig.json, common/changes/@binaris/shift-babel-macro/unify-tsconfig_2019-07-11-10-31.json, common/changes/@binaris/shift-db/unify-tsconfig_2019-07-11-10-31.json, common/changes/@binaris/shift-fetch-runtime/unify-tsconfig_2019-07-11-10-31.json, common/changes/@binaris/shift-local-proxy/unify-tsconfig_2019-07-11-10-31.json, common/changes/rush-update/unify-tsconfig_2019-07-11-10-31.json, common/tsconfig.json, db/tsconfig.json, fetch-runtime/tsconfig.json, local-proxy/tsconfig.json, tools/rush-update/tsconfig.json
Preparation before adding yet another tsconfig.
=> Unify tsconfigs by extending a common config

common/changes/@binaris/shift-fetch-runtime/stricter-linter_2019-07-30-09-09.json, common/changes/@binaris/shift-react-app/stricter-linter_2019-07-30-09-09.json, common/changes/rush-update/stricter-linter_2019-07-30-09-09.json, common/tslint.yml, fetch-runtime/src/index.ts, shift-react-app/src/shiftReactApp.ts, shift-react-app/src/test/shiftReactApp.spec.ts, tools/rush-update/src/types.d.ts
Discovered when writing an async function and forgetting to await
Also add await-promise rule
=> Enable more tslint strict rules

common/changes/@binaris/shift-db/unserializable_2019-08-04-07-51.json, common/config/rush/shrinkwrap.yaml, db/src/db.ts, db/src/test/db.spec.ts
=> [db] Disallow all non-JSONable types at top level of values 

code-transform/macro.js, common/changes/@binaris/shift-code-transform/restore-macro-file_2019-08-08-12-17.json
Needed for pretty imports of 'code-transform/macro'.
=> Restore missing macro.js file

common/changes/@binaris/shift-local-proxy/gen-source-maps_2019-08-09-07-35.json, local-proxy/src/server.ts
Improve debugging (allow breakpoints in backend sources)
=> Generate source maps for transpiled backend sources

common/changes/@binaris/shiftjs-react-app/install-serving-function_2019-08-13-11-07.json, shiftjs-react-app/src/steps.ts
=> Add shift-server-function to install script

cli/README.md, cli/package.json, common/changes/shift-cli/update-cli_2019-08-13-11-33.json
The publish script does not commit the README.md, so adding it separately.
=> Update CLI Readme

common/config/rush/shrinkwrap.yaml, common/tslint.yml
Broke all linting this morning.
=> Remove empty jsRules: breaks tslint ^5.19.0

cli/README.md
Manual until integrated into publish process
=> Update cli README after publish

cli/package.json, common/changes/shift-cli/update-log-types_2019-08-22-17-03.json, common/config/rush/shrinkwrap.yaml
=> Update logs interfaces to accept logs format

cli/src/commands/logs.ts, cli/src/utils/cli-flags.ts, cli/tsconfig.json, common/changes/shift-cli/master_2019-08-20-17-37.json, common/config/rush/shrinkwrap.yaml
unfortunately only tested manually
=> Fix log limits

cli/src/utils/cli-flags.ts, common/changes/shift-cli/fix-log-limits_2019-08-26-12-00.json
as requested in #154 
manually tested similar to 154
=> Clean cli min max flags

cli/src/commands/deploy.ts, common/changes/shift-cli/app-https-link_2019-08-27-10-02.json
Print only the URL on unsupporting terminals
=> Use terminal-link for deployed message

common/changes/@binaris/shiftjs-react-app/master_2019-08-28-17-01.json, common/config/rush/shrinkwrap.yaml, shiftjs-react-app/src/steps.ts
Seems it was missing from the db update, and not caught due to missing end to end tests.
=> Add local db server to packages

cli/README.md, cli/package.json, cli/src/commands/browse.ts, cli/src/commands/list.ts, cli/src/commands/logs.ts, cli/src/commands/whoami.ts, cli/src/missing.d.ts, common/changes/shift-cli/master_2019-08-29-12-38.json, common/config/rush/shrinkwrap.yaml
unfortunately only tested manually.
`./bin/run list a`
`./bin/run list --a`
`./bin/run list`
`./bin/run whoami`
`./bin/run browse`
also with fake templates data and extra flag/arg to whoami and browse commands
=> Add list, browse and whoami CLI commands

cli/README.md, cli/package.json, cli/src/commands/claim.ts, cli/src/commands/deploy.ts, cli/src/commands/list.ts, cli/src/commands/login.ts, cli/src/commands/try.ts, cli/src/commands/whoami.ts, common/changes/shift-cli/master_2019-09-01-21-43.json, common/config/rush/shrinkwrap.yaml
manually tested with matching binaris/spice#644
=> Add try and claim CLI commands

cli/README.md, cli/package.json, cli/src/commands/destroy.ts, common/changes/shift-cli/master_2019-09-02-21-55.json, common/config/rush/shrinkwrap.yaml
=> Add destroy app command

.circleci/config.yml, cli/package.json, cli/src/test/cli.spec.ts, common/changes/shift-cli/cli-test_2019-09-04-06-50.json, common/config/rush/shrinkwrap.yaml
Need (at least) `remove` command to be able to test `deploy`, `logs`.
=> Initial CLI tests (usage)

.circleci/config.yml
=> Generate interface packages for update npm dependencies task

common/changes/@binaris/shift-server-function/serve-204_2019-09-08-12-35.json, server-function/src/serveBinaris.ts
For feature parity with local-proxy
=> Return statusCode 204 on empty responses

cli/src/commands/deploy.ts, common/changes/@binaris/shift-local-proxy/backend-deploy-non-js_2019-09-02-15-11.json, common/changes/shift-cli/backend-deploy-non-js_2019-09-02-15-11.json, common/config/rush/shrinkwrap.yaml, local-proxy/package.json, local-proxy/src/server.ts
Also allow access to non-JS files in backend directory from local-proxy
Discovered by @rylandg
=> Deploy non-JS files of backend directory

docs/tf/cdn.tf
=> Redirect viewers from http to https

common/changes/@reshuffle/local-proxy/no-bunyan_2019-09-23-13-31.json, common/config/rush/shrinkwrap.yaml, local-proxy/package.json, local-proxy/src/server.ts, local-proxy/src/stdio.ts
No longer require binary dtrace-provider dependency
Include pid in logs
Update log name
Fixes #212
=> Replace bunyan with winston 

common/changes/@reshuffle/db/rm-cli-dep_2019-09-23-13-55.json, db-client/package.json
Generated docs output seems unaffected
@arielshaqed PTAL since this was introduced in https://github.com/reshufflehq/reshuffle/commit/7104cce91f2124f7efd8a9e6a557917e77a6c362
=> Remove db-client cli dep

cli/src/utils/getdeps.ts, common/changes/reshuffle/no-code-transform-dep_2019-09-23-17-13.json
=> Exclude code-transform from deployed files

common/changes/@reshuffle/leveldb-server/local-initial-data_2019-09-24-16-25.json, common/changes/@reshuffle/local-proxy/local-initial-data_2019-09-24-16-25.json, leveldb-server/src/db.ts, leveldb-server/src/test/client.test.ts, leveldb-server/src/test/initialData.spec.ts, local-proxy/src/index.ts, local-proxy/src/server.ts
This is probably missing some edge cases, but has the behavior in place
=> Insert initial data locally if db not initialized 

cli/package.json, cli/src/commands/deploy.ts, cli/src/commands/destroy.ts, cli/src/commands/download.ts, cli/src/test/destroy.spec.ts, cli/src/test/download.spec.ts, cli/src/test/fake_lycan.ts, common/changes/reshuffle/feature-reschema_2019-09-25-08-50.json, common/config/rush/shrinkwrap.yaml
Goes with the discussed changes to spice
=> Update spice client to exclude name from deployInitial

Jenkinsfile
On Jenkins in addition to CircleCI
=> Skip building ephemeral publish- branch

cli/package.json, common/changes/reshuffle/bump-specshell_2019-10-02-19-39.json, common/config/rush/shrinkwrap.yaml
This version has (only) build and packaging changes.
=> Bump specshell version

cli/src/utils/command.ts, common/changes/reshuffle/allow-open-fail_2019-10-06-13-04.json
Better support headless environments
Should help with #226.
=> Allow errors when automatically opening browser

common/changes/@reshuffle/fetch-runtime/non-react_2019-10-23-15-53.json, fetch-runtime/src/index.ts
PUBLIC_URL only defined in create-react-app, assume / if undefined
=> Allow PUBLIC_URL to be undefined

cli/package.json, common/changes/@reshuffle/local-proxy/rm-types-dotenv_2019-11-08-05-04.json, common/changes/reshuffle/rm-types-dotenv_2019-11-08-05-04.json, common/config/rush/shrinkwrap.yaml, local-proxy/package.json
dotenv package now provides the types
=> Remove deprecated @types/dotenv package

common/changes/@reshuffle/local-proxy/master_2019-11-13-12-01.json, common/changes/@reshuffle/local-proxy/master_2019-11-13-12-32.json, common/config/rush/shrinkwrap.yaml, local-proxy/package.json
Couldn't find a way to define  dependency as peer via rush itself, so simply changed the package json file.
=> Make server-function a peer dependency of local-proxy

app-testsuite/package.json, app-testsuite/src/run.ts, common/changes/@reshuffle/local-proxy/local-proxy-exec_2019-11-14-09-18.json, common/config/rush/shrinkwrap.yaml, local-proxy/package.json, local-proxy/src/localServer.ts
For running without create-react-app
Used in a package.json as { "start": "reshuffle-local-server" }
=> Add reshuffle-local-server helper script

cli/src/utils/getdeps.ts, common/changes/reshuffle/package-lock-parsing-fixes_2019-11-17-11-34.json
Tested on next demo app and marketplace-cms koa
=> Fix package lock parsing for nested deps

common/changes/@reshuffle/passport/master_2019-11-19-12-41.json, passport/src/auth-handler.ts
See https://auth0.com/docs/logout for more details
=> Proprly logout from OAUTH provider

common/changes/@reshuffle/react-auth/react-auth-commonjs_2019-11-20-10-07.json, common/config/rush/shrinkwrap.yaml, react-auth/.gitignore, react-auth/package.json, react-auth/tsconfig.json
Similar to react-async-hooks configuration
Required for Jest test runner
=> Output CommonJS for react-auth

common/changes/@reshuffle/passport/bump-passport_2019-11-20-15-06.json
To allow basic patches support from semver
=> Update passport to v0.1.0

common/changes/@reshuffle/passport/proposal-handler-not-router_2019-11-20-18-25.json, passport/src/auth-handler.ts, passport/src/index.ts, passport/src/test/local.test.ts
To be similar in style with defaultHandler
=> Export a pre-created authHandler

cli/src/commands/claim.ts, cli/src/commands/deploy.ts, cli/src/commands/list.ts, cli/src/utils/helpers.ts, common/changes/reshuffle/master_2019-11-24-17-42.json
Tested on my realm (which has multiple domains)
=> Use primary domain in the CLI

cli/src/commands/add-domain.ts, cli/src/commands/destroy.ts, cli/src/commands/info.ts, cli/src/commands/remove-domain.ts, cli/src/utils/command.ts, common/changes/reshuffle/info_2019-12-01-14-11.json
tested manually by adding and removing domain, as well as printing app information before, after, and during the process
=> Add info, add-domain, and remove-domain hidden commands

cli/src/utils/helpers.ts, common/changes/reshuffle/master_2019-12-02-12-18.json
manually tested by deploying both with and without custom domains
=> Show connected custom domain after deploy if exists

common/changes/@reshuffle/db-testsuite/configure-thoth-auth-token_2019-12-02-16-08.json, common/config/rush/shrinkwrap.yaml, db-testsuite/src/client.ts
*Real* Thoth tokens sign the application ID.  So token cannot be
constant.  Instead pass a function that builds it.
=> Allow configuring authentication token in test DB client (take 2)

cli/package.json, cli/src/utils/cli-flags.ts, common/changes/reshuffle/update-validator_2019-12-22-11-52.json, common/config/rush/shrinkwrap.yaml
=> Update validator package

app-testsuite/app/src/App.js, app-testsuite/cypress/integration/full_spec.js, app-testsuite/src/run.ts
This fixes a race condition with HTML loading before react rendering
=> Ensure runningOn element exists before calling then

common/changes/@reshuffle/labs-db-iterator/db-iterator_2020-01-15-13-52.json, common/config/rush/shrinkwrap.yaml, labs/README.md, labs/db-iterator/README.md, labs/db-iterator/package.json, labs/db-iterator/src/index.ts, labs/db-iterator/src/iterator.spec.ts, labs/db-iterator/src/iterator.ts, labs/db-iterator/tsconfig.json, rush.json
Initial version to gauge usefulness of the interface.  In particular,
this does _not_ view a snapshot -- items added during iteration might
appear (or they might not).
=> Add DB iterator

index.js, lib/index.js
=> Reshuffle package - fix export of default services

index.js
Allow chaining in the form of
`const httpService = app.register(new HttpService());`
=> Allow chaining

docs/building-connectors.md, docs/connectors.md
Added smtp
Updated build connector tutorial
=> Updates to docs

src/connectors/CronConnector.ts, src/connectors/HttpConnector.ts, src/connectors/SlackConnector.ts
3 TS error because of `on` signature different from baseConnector class
=> Connector on method returns an EventConfiguration

.gitignore, jest.config.js, package-lock.json, package.json, src/Reshuffle.ts, src/connectors/CronConnector.ts, src/connectors/HttpConnector.ts, test/CronConnector.spec.ts, test/Reshuffle.spec.ts
more unit tests to come for HttpConnector and CronConnector but this initial PR covers Reshuffle and Logger at 100%
=> Run 1 unit tests init

src/persistency/SQLStoreAdapter.ts
Added a db existence check to the list operation
=> Check database on list

examples/http-typescript/HTTPExample.ts, examples/http-typescript/package-lock.json, examples/http-typescript/package.json, examples/http-typescript/tsconfig.json
Add an HTTP example for Typescript to address #478
=> add http-typescript example

examples/monday/Monday.js
Some minor updates to reflect the API changes made over the last few months.
=> Updates to the Monday example code to reflect reshuffle API changes

README.md
Current link is pointing to a non-existent subdomain.
=> Fix broken link to tutorial
