.circleci/config.yml
babel-macro/jest.config.js
babel-macro/package.json
common/changes/@binaris/shift-babel-macro/test-command_2019-07-01-09-13.json
common/config/rush/command-line.json
common/config/rush/shrinkwrap.yaml

Changes to #51 - replace bash with a rush command.

 Add rush test command

---

common/changes/@binaris/shift-db/types-d-ts_2019-07-17-13-59.json
db/package.json

As noted in https://github.com/binaris/shiftjs/pull/95#discussion_r304296807, `"types"` looks at a `.d.ts` file ...

Refer to actual file for types

---

babel-common/package.json
babel-common/src/index.ts
babel-common/tsconfig.json
babel-macro/package.json
babel-macro/src/macro.ts
babel-plugin/README.md
babel-plugin/ignored.d.ts
babel-plugin/jest.config.js
babel-plugin/package.json
babel-plugin/src/index.ts
babel-plugin/src/test/plugin.spec.ts
babel-plugin/tsconfig.json
common/changes/@binaris/shift-babel-common/babel-plugin_2019-07-16-11-34.json
common/changes/@binaris/shift-babel-macro/babel-plugin_2019-07-16-11-34.json
common/changes/@binaris/shift-babel-plugin/babel-plugin_2019-07-16-11-34.json
common/changes/@binaris/shift-backend-babel-plugin/babel-plugin_2019-07-16-11-34.json
common/config/rush/shrinkwrap.yaml
rush.json

Only implements basic exposed functions (no typescript support)
This introduces the first inter-dependency within the shiftjs repo - now any changes to `babel-common/` will publish a new version of `@binaris/shift-babel-common` and new versions of dependants `@binaris/shift-babel-macro` and `@binaris/shift-babel-plugin`. The dependencies are for exact versions so all modules are upgraded in sync.

Add initial babel-plugin code

---

common/changes/@binaris/shift-local-proxy/cleanup-sigint_2019-07-18-13-51.json
local-proxy/src/server.ts

To avoid confusing leftover .shift_local_proxy_ directories

Cleanup temp directories when ctrl-c is used in terminal 

---

.circleci/config.yml

Publish branches are temporarily created by rush during publish process
before being merged into the master branch
By the time circleci starts processing the branch it is already deleted,
causing noisy errors in logs
For some reason `yq` breaks on the `jobs` section `.circleci/config.yml`, tested with`$ js-yaml .circleci/config.yml`.

Ignore publish- branches

---

scripts/generate_interfaces

Which needs to be manually removed each time

Avoid creating interfaces/package-lock.json

---

common/changes/@binaris/shiftjs-react-app/moar-timeout_2019-08-08-10-59.json
shiftjs-react-app/src/test/shiftReactApp.spec.ts

Installing all create-react-app packages from npm takes a varying time,
sometimes going above 60 seconds

Increase install test timeout

---

cli/README.md
cli/package.json
cli/src/commands/logs.ts
cli/src/utils/command.ts
common/changes/shift-cli/cli-fix-parsing_2019-08-15-15-30.json
common/config/rush/shrinkwrap.yaml

Otherwise unknown in this context but valid extra flags are not recognized
Also add chalk as dependency to help when running with rush

Use non-strict parsing when parsing BaseCommand flags

---

.gitattributes
common/config/rush/shrinkwrap.yaml

This lets GitHub hide diffs in it by default.
Also my teleprinter is broken: get rid of CRs.
It looks like this (I pushed a bad change to shrinkwrap and now I'm resetting it, so you can see for yourself on this very PR):

Tell Linguist (and GitHub) that shrinkwrap.json is generated

---

common/changes/@binaris/shift-local-proxy/upstream-nodemon_2019-08-21-14-14.json
common/config/rush/shrinkwrap.yaml
local-proxy/package.json
local-proxy/src/index.ts

There are no new actual upstream changes
Use a more precise version number
Prevent various npm bugs installing npm packages

Use upstream nodemon

---

cli/src/commands/deploy.ts
common/changes/shift-cli/deploy-less_2019-08-23-18-18.json

Avoid a flattened copy of build folder
Ignore all .dotfiles
Avoid adding bundle.tgz to bundle.tgz

Upload less files

---

db-client/src/index.ts
db-client/src/test/component/db.ts
local-proxy/src/server.ts

Use `SHIFT_*` environment variables.  These are passed on the actual
runtime.

Environment variables should start with SHIFT_ and match runtime

---

common/changes/@binaris/shift-db/no-return-await_2019-08-28-09-21.json
common/changes/@binaris/shift-leveldb-server/no-return-await_2019-08-29-08-09.json
common/tslint.yml
db-client/src/db.ts
db-client/src/index.ts
leveldb-server/src/db.ts

Perf: do not create extra promises
Ensure code is consistent (without the rule both variants are valid)

Add no-return-await rule

---

common/changes/@binaris/shift-local-proxy/local-proxy-host-check_2019-09-01-14-13.json
common/changes/@binaris/shift-server-function/local-proxy-host-check_2019-09-01-14-13.json
common/config/rush/shrinkwrap.yaml
local-proxy/package.json
local-proxy/src/index.ts
local-proxy/src/test/corsNotAllowed.test.ts
local-proxy/src/test/flakyInvoke.test.ts
local-proxy/src/test/invalidHost.test.ts
local-proxy/src/test/nonWhitelistedNotAllowed.test.ts
local-proxy/src/test/setupHooks.ts
server-function/src/index.ts
server-function/src/serveBinaris.ts
server-function/src/test/serve.test.ts

This is re-implementing the webpack-dev-server checks so that they are
available both locally and remotely
Fixes #98.

Enable host and origin checks in local and remote serving

---

code-transform/src/common.ts
common/changes/@binaris/shift-code-transform/nocompile_2019-09-08-12-36.json

Instead:
1. In one instance _explicitly_ type out the desired `leadingComments`
field (to identify comments with `@expose`),
2. In the other instance use `object`: `isExpressionStatement` anyway
expects that type and will cast to an `ExpressionStatement`.

Don't use unexported type BabelTypes.BaseNode

---

common/changes/@binaris/shift-server-function/republish-server-function_2019-09-09-09-03.json

Force republish of `@binaris/shift-server-function` (was published as 0.0.3 on septemeber 4 but can't republish immutable version)

Dummy change

---

common/changes/@binaris/shiftjs-react-app/rm-leveldb-direct-dep_2019-09-09-16-35.json
shiftjs-react-app/src/steps.ts

The package is installed as a dependency of local-proxy, it shouldn't
be required as a direct dependency
This essentially reverts #179

Remove @binaris/shift-leveldb-server

---

common/changes/@reshuffle/react-app/shebang_2019-09-18-04-27.json
react-app/src/reactApp.ts

Without it gets interpreted as shell

Add missing shebang

---

common/changes/@reshuffle/db/docs_2019-09-19-14-47.json
common/config/rush/shrinkwrap.yaml
db-client/.gitignore
db-client/API.md
db-client/package.json
db-client/tsconfig.json
docs/.gitignore
docs/package.json
docs/tf/backend.tf
docs/tf/cdn.tf
docs/tf/main.tf
docs/tf/variables.tf
docs/tf/www_bucket.tf

This is auto-generated from TSDoc-like annotations on `db-client`; it gives us _something_.  You can see what on http://dev-docs.reshuffle.com/ (which is also how I tested it).
It turns out that there are no good simple documentation tools for tsdoc.  We use TypeDoc, which is the best I could find with minimal setup.  It has limitations; we shall need either to work around or fix them.
Alternatives considered:
1. Microsoft do The Real TsDoc:tm:.  This will be great, but is not yet: they have a parser, but haven't even documented the format, and there is no "publish docs from this directory" tool.  Also the format is more limited than that for typedoc.  There are additional tools based on API Extractor, but I was unable to get them to work.
2. Angular have dgeni; this is what's used by …

Add API-level documentation

---

.circleci/config.yml

Comment allows removing after packages are public
This can allow us to check accidental usage of private packages

Remove npm token

---

common/changes/@reshuffle/leveldb-server/feature-bug-immutable-errors_2019-09-24-05-59.json
leveldb-server/src/db.ts
leveldb-server/src/test/client.test.ts

Don't touch immutable `Error`s, copy them instead.  Resulting error
looks like this:
```
Failed to invoke function { InternalServerError: [6hMvBxG47sy90hXscv-DJ] Database is not open
at DBClient.get (/Users/ariels/Google Drive/Work/Dev/counter-class-master/node_modules/@reshuffle/interfaces-node-client/client.js:108:19)
at process._tickCallback (internal/process/next_tick.js:68:7) name: 'InternalServerError' }
InternalServerError: [6hMvBxG47sy90hXscv-DJ] Database is not open
at DBClient.get (/Users/ariels/Google Drive/Work/Dev/counter-class-master/node_modules/@reshuffle/interfaces-node-client/client.js:108:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
Fixes #255.
Tested (see above) by manually linking and running 2 conncurrent local
servers.
However I *cannot* …

Prettify LevelDB errors correctly

---

cli/src/utils/command.ts
common/changes/reshuffle/download-analytics_2019-09-26-06-56.json

I thought it would be clearer to `then` a function that does nothing,
the #266  code review proved me wrong.
Then I forgot to include it in the fixes.  Sorry.

CR: Do literally nothing when dropping promise resolution

---

cli/src/commands/deploy.ts
cli/src/utils/command.ts
common/changes/reshuffle/timedeploy_2019-10-03-07-52.json
common/config/rush/shrinkwrap.yaml

- Output on debug, need to set e.g. `DEBUG` envariable to match
`reshuffle:deploy`.
- Last output so all timings appear together -- useful if you just
`DEBUG=\*` before the deploy command.
- OClif actually measures times between `debug` calls.  But using that
means you need to be very careful how you set `DEBUG` (i.e. it's
useful as a by-product when logging debug, less if your intent is to
measure performance).
Output looks like this:
```
flutterby:counter-class ariels$ DEBUG='reshuffle:deploy' ~/Dev/reshuffle/cli/bin/run deploy
Building and bundling your app! This may take a few moments, please wait
> counter-class@0.1.2 build /Users/ariels/Google Drive/Work/Dev/counter-class
> react-scripts build
Creating an optimized production build...
Compiled successfully.
File sizes after gzip: …
```

Measure stage timings during deploy

---

cli/src/commands/download.ts
common/changes/reshuffle/feature-download-no-tmp_2019-10-06-10-43.json

Fixes these issues (due to @vogre, no actual user-facing issues filed):
1. When `/tmp/` (or whatever temporary directory is used) is on
another directory, there is _no_ atomic rename from the temporary
directory into the current directory.
2. Write permissions on the temporary directory were needed.
This may fix (or at least aid) using `[cli] deploy` on Windows.

Download into local directory, not tmp

---

.circleci/config.yml
common/changes/rush-update/rush-update-exclude-packages_2019-10-22-12-06.json
tools/rush-update/src/cli.ts
tools/rush-update/src/main.ts
tools/rush-update/src/rush.ts

Exclude concord generated/generating packages from auto-update
To allow PRs like #284 to work again.

Add --exclude-packages flag to exclude some packages from auto-update 

---

app-testsuite/src/run.ts

Cypress expects to be installed as root for sandbox permissions
npx only works with node user in testing.Dockerfile
Consider switching to cypress docker image when available

Lock cypress version to 3.4.1

---

cli/src/commands/deploy.ts
cli/src/utils/babelBackendConfig.ts
common/changes/@reshuffle/local-proxy/babel-backend-config_2019-11-07-19-22.json
common/changes/reshuffle/babel-backend-config_2019-11-07-20-26.json
local-proxy/src/babelBackendConfig.ts
local-proxy/src/server.ts

Usually a non-CRA front-end project will contain a babel.config.js which
front-end oriented configuration (e.g. regenerator-runtime).
This only provides an empty configuration, could be extended in the
future to allow custom backend babel configuration (e.g. more plugins)

Use an explicit configFile for babel backend config

---

cli/src/commands/deploy.ts
common/changes/@reshuffle/local-proxy/source-map-support_2019-11-11-07-35.json
common/changes/@reshuffle/server-function/source-map-support_2019-11-07-22-51.json
common/changes/reshuffle/source-map-support_2019-11-07-22-51.json
common/config/rush/shrinkwrap.yaml
local-proxy/package.json
local-proxy/src/missing.d.ts
local-proxy/src/test/errorHandler.test.ts
local-proxy/src/test/fixture/backend/testStackTrace.js
local-proxy/src/test/setupHooks.ts
server-function/package.json
server-function/src/invoke.ts
server-function/src/serveBinaris.ts

This change puts the source-map-support in the uploaded serveBinaris
file, so that the support is enabled in both local and remote runtimes
The price of this change is upload of source-map(-support) which adds
944K (230K compressed) to the upload

Enable source map support

---

common/changes/@reshuffle/code-transform/bump-semver_2019-11-11-22-03.json
common/changes/@reshuffle/db-testsuite/bump-semver_2019-11-11-22-03.json
common/changes/@reshuffle/fetch-runtime/bump-semver_2019-11-11-22-03.json
common/changes/@reshuffle/leveldb-server/bump-semver_2019-11-11-22-03.json
common/changes/@reshuffle/server-function/bump-semver_2019-11-11-22-06.json

Allow releasing semver compatible versions without releasing 1.0.0 yet
Instead of #312

Bump version to 0.1.0

---

.circleci/config.yml
cli/package.json
common/changes/reshuffle/downgrade-chalk-dep_2019-11-17-15-54.json
common/config/rush/shrinkwrap.yaml

Major version increase makes it incompatible with @oclif/color (not
currently causing any issues in our usage of color display, but confuses
the node_modules structure)
Reverts part of #318.

Downgrade chalk package version

---

cli/package.json
common/changes/reshuffle/feature-downgrade-interfaces_2019-11-20-13-49.json
common/config/rush/shrinkwrap.yaml

This does not require a republish (since the package.json uses a caret and does not have a `shrinkwrap` file or `pkg` to package the CLI)

Downgrade spice-node-client

---

cli/src/test/download.spec.ts
common/changes/reshuffle/test-serial-download_2019-11-20-17-54.json

Download tests use separate shells, but use a common $HOME/.npm folder
when installing app, sometimes resulting in collisions

Run download tests in serial

---

common/changes/@reshuffle/react-auth/feature-better-_handler-error-message_2019-11-21-08-41.json
react-auth/src/index.tsx

When the backend is misconfigured and `_handler` is missing the
default backend does not give a JSON response.  Fail accordingly and
print a readable error message.
This is end-user-visible, of course -- but so is the existing behavior of
printing
```
SyntaxError: Unexpected token < in JSON at position 0
```

Clearly report backend misconfiguration

---

common/changes/@reshuffle/passport/auth-multiple-strategies_2019-12-01-06-04.json
passport/src/auth-handler.ts
passport/src/strategy.ts

Attempting to use the module without matching the domain name changes
the behavior to 404, since we don't fallback to a default domain - and
for security purposes probably shouldn't

Support per-domain auth strategies

---

app-testsuite/src/run.ts

When using yarn it takes longer to install the @reshuffle packages since
it forces a full reinstall

Force app-testsuite to create-react-app with npm

---

cli/src/utils/command.ts
common/changes/reshuffle/up-to-date-verify_2019-12-21-11-16.json

May not be 100% correct all the time, as response validation may fail
for other reasons, but it should be the most common cause.

Add comment about checking CLI version

---

common/changes/@reshuffle/local-proxy/dotenv-location_2020-01-09-15-39.json
local-proxy/src/index.ts
local-proxy/src/server.ts

This does not affect projects using create-react-app, since
create-react-app populates process.env before reaching reshuffle code
Tested using reshuffle-local-server which does not use dotenv before

Use project root as .env file location

---

examples/http/HTTPExample.js
examples/http/registerUnregisterHTTPExample.js
src/connectors/HttpConnector.ts

Fix HTTPConnector to call handle with an event that has system attributes under context

Use event.context with HttpConnector 

---

src/connectors/HttpConnector.ts

The logging (a) did not contribute a thing and (b) slowed down soak tests by almost a 2x factor

Improve HTTP Connector performance

---

src/Reshuffle.ts

It's handy to be able to add middleware to the express webserver in some circumstances. A few examples:
- adding a health check URL (currently hardcoded into `Reshuffle.ts` but could be removed in future)
- adding in custom middleware such as a **`cookie-parser`**

Allow custom middleware to be added to the express webserver
